"""Build downloadable ESPHome firmware artifacts from the panel data.

Three flavors:
  - snippet: just the substitutions block (existing behavior)
  - full:    the user's complete energy_meter.yaml with our substitutions merged in
  - zip:     the full YAML + a secrets template + a README, in one bundle
"""
from __future__ import annotations

import io
import re
import zipfile
from typing import Any

from . import db
from . import panel as panel_mod


# ---------------------------------------------------------------------------
# Substitutions snippet (kept for the "copy a block" flow)
# ---------------------------------------------------------------------------

def snippet(panel_data: dict[str, Any]) -> str:
    return panel_mod.yaml_export(panel_data)


# ---------------------------------------------------------------------------
# Full YAML — merges our generated substitutions into the user's stored YAML.
#
# Strategy: line-level rewrite of `ctN_name:` and `current_cal_ctN:` inside the
# substitutions: block. Anything else (voltage_cal, sign-inversion filters,
# packages, esphome:, etc.) is preserved exactly as the user has it. Comments
# the user wrote on those lines are kept. New ports/CTs that didn't exist in
# the original substitutions are appended at the end of the substitutions
# block.
# ---------------------------------------------------------------------------

# A baseline used only when the user hasn't pasted their YAML yet. Generic
# enough to compile against the upstream CircuitSetup package; no secrets.
# Placeholders use __NAME__ markers (replaced via str.replace) to avoid clashes
# with the YAML's own ${...} substitution syntax.
_SKELETON = """\
# CircuitSetup 6-Channel Energy Meter Main Board + 1 Add-on Board
# Generated by panel-tool. Edit secrets.yaml separately.

substitutions:
  disp_name: energy-meter
  friendly_name: "Energy Meter"
  update_time: 10s
  electric_freq: "60Hz"

## Main board
  main_meter_name1: Meter 1-3
  main_meter_name2: Meter 4-6
  main_meter_id1: meter_main1
  main_meter_id2: meter_main2
__CT_MAIN_NAMES__

## Add-on board
  addon1_name1: Addon1 7-9
  addon1_name2: Addon1 10-12
  addon1_id1: addon1_1
  addon1_id2: addon1_2
__CT_ADDON_NAMES__

## Calibration
  offset_calibration: "true"
  gain_calibration: "true"

__CT_MAIN_CALS__
__CT_ADDON_CALS__

  voltage_cal1: '7305'
  voltage_cal2: '7305'

esphome:
  name: ${disp_name}
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  min_version: '2025.7.0'
  project:
    name: circuitsetup.6c-energy-meter-1-addon
    version: "1.7"

packages:
  remote_package:
    url: https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter
    ref: master
    refresh: 1d
    files:
      - Software/ESPHome/6chan_common.yaml
      - Software/ESPHome/meter_sensors/6chan_main_sensor.yaml
      - Software/ESPHome/meter_sensors/6chan_addon1.yaml
      - Software/ESPHome/status_fields/6chan_main_status.yaml
      - Software/ESPHome/calibration/6chan_main_calibration.yaml
      - Software/ESPHome/calibration/6chan_addon1_calibration.yaml

dashboard_import:
  package_import_url: github://CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/Software/ESPHome/6chan_energy_meter_1-addon.yaml@master
  import_full_config: true

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_improv:
  authorizer: none

improv_serial:

web_server:
  port: 80
"""


def _by_port(panel_data: dict[str, Any]) -> dict[int, dict[str, Any]]:
    return {ct["port"]: ct for ct in panel_data.get("cts", []) if ct.get("port")}


def _build_skeleton(panel_data: dict[str, Any]) -> str:
    by_port = _by_port(panel_data)

    def name_lines(start: int, end: int) -> str:
        out = []
        for port in range(start, end + 1):
            ct = by_port.get(port)
            label = (ct.get("label") if ct else "") or f"CT{port}"
            out.append(f"  ct{port}_name: {label}")
        return "\n".join(out)

    def cal_lines(start: int, end: int) -> str:
        out = []
        for port in range(start, end + 1):
            ct = by_port.get(port)
            cal = panel_mod.CT_MODEL_CAL.get(ct.get("model"), "8650") if ct else "8650"
            out.append(f"  current_cal_ct{port}: '{cal}'")
        return "\n".join(out)

    return (_SKELETON
            .replace("__CT_MAIN_NAMES__",  name_lines(1, 6))
            .replace("__CT_ADDON_NAMES__", name_lines(7, 12))
            .replace("__CT_MAIN_CALS__",   cal_lines(1, 6))
            .replace("__CT_ADDON_CALS__",  cal_lines(7, 12)))


def _replace_or_append(text: str, key: str, value_line: str) -> str:
    """Replace `^  {key}:.*$` line in text, or, if absent, append it inside
    the substitutions: block (just before the next top-level key)."""
    pattern = rf"^(\s+){re.escape(key)}:[^\n]*$"
    m = re.search(pattern, text, flags=re.MULTILINE)
    if m:
        indent = m.group(1)
        return text[: m.start()] + f"{indent}{key}: {value_line}" + text[m.end():]
    # Append before the line that ends the substitutions: block.
    sub_match = re.search(r"^substitutions:\s*$", text, flags=re.MULTILINE)
    if not sub_match:
        return text  # no substitutions block; can't safely insert.
    # Find first non-substitutions top-level key after substitutions:.
    after = text[sub_match.end():]
    next_key = re.search(r"^[a-zA-Z_]+:", after, flags=re.MULTILINE)
    insertion_point = sub_match.end() + (next_key.start() if next_key else len(after))
    return text[:insertion_point] + f"  {key}: {value_line}\n" + text[insertion_point:]


def merge_full_yaml(panel_data: dict[str, Any]) -> str:
    """Return a complete energy_meter.yaml with our substitutions merged into
    whatever YAML the user pasted at /setup. Falls back to a skeleton if no
    YAML is stored."""
    base = db.get_setting("esphome_yaml") or ""
    if not base.strip():
        return _build_skeleton(panel_data)

    out = base
    by_port = _by_port(panel_data)
    for port in range(1, 13):
        ct = by_port.get(port)
        label = (ct.get("label") if ct else "") or f"CT{port}"
        cal = panel_mod.CT_MODEL_CAL.get(ct.get("model"), "8650") if ct else "8650"
        out = _replace_or_append(out, f"ct{port}_name", label)
        out = _replace_or_append(out, f"current_cal_ct{port}", f"'{cal}'")
    return out


# ---------------------------------------------------------------------------
# ZIP bundle
# ---------------------------------------------------------------------------

_SECRETS_TEMPLATE = """\
## Edit these and rename to secrets.yaml.
##
## Generate the encryption + OTA values with:
##   openssl rand -base64 32

wifi_ssid:    "YOUR_WIFI_SSID"
wifi_password: "YOUR_WIFI_PASSWORD"

api_encryption_key: "PASTE-A-FRESH-32-BYTE-BASE64-VALUE-HERE="
ota_password:       "PASTE-A-FRESH-RANDOM-PASSWORD-HERE"
"""


_README_TEMPLATE = """\
# Flashing your CircuitSetup energy meter

These three files were generated by panel-tool. Save them to a directory
on your laptop, edit `secrets.yaml.example`, then flash one of two ways:

## Option 1 — local flashing with the ESPHome CLI

```
# install once
pip install esphome

# from the directory holding these files
mv secrets.yaml.example secrets.yaml
$EDITOR secrets.yaml         # fill in WiFi + generate keys per the comments
esphome run energy_meter.yaml
```

The first compile downloads PlatformIO (~5 min). Subsequent compiles take
about 60s. The `run` command both compiles and uploads — it will prompt
for OTA upload if the device is already on Wi-Fi.

## Option 2 — Home Assistant ESPHome add-on

If your Home Assistant install has the ESPHome add-on:

1. Open the ESPHome dashboard.
2. New device → upload `energy_meter.yaml`.
3. Edit the device's YAML and **also** upload your filled-in `secrets.yaml`
   to the add-on's secrets store.
4. Click *Install* → *Wirelessly*.

## File summary

| File | What it is |
|---|---|
| `energy_meter.yaml` | The full firmware config. CT names + cal values reflect the panel-tool state at export time. |
| `secrets.yaml.example` | Template for WiFi credentials, the API encryption key (HA pairing), and the OTA password. Edit and rename to `secrets.yaml`. |
| `README.md` | This file. |

Re-run the export from panel-tool any time the panel mapping changes. The
substitutions block gets rewritten; everything else (voltage cal,
sign-inversion filters, packages) is preserved from your previously-pasted
YAML.
"""


def build_zip_bytes(panel_data: dict[str, Any]) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("energy_meter.yaml", merge_full_yaml(panel_data))
        zf.writestr("secrets.yaml.example", _SECRETS_TEMPLATE)
        zf.writestr("README.md", _README_TEMPLATE)
    return buf.getvalue()
